### ISSUE TITLE
Pre-Launch "content cleanup" checklist (SD Engineers)

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#116]
- [ ] Search for Smartpay to ensure P is capitalized everywhere
- [ ] Make sure "GSA" precedes _every_ reference to SmartPay
- [ ] Ensure that the (R) mark is only used on the first reference on each page / document

**Comment by weiwang-gsa** [comment]
@JessicaMarine1 when I working on it, i found email subject is using GSA SmartPayⓇ, but in training content, it is using GSA SmartPay®, email's R is slightly bigger than training content, should update email subject to use smaller R to be consistent with training content?

**Comment by JessicaMarine1** [comment]
@weiwang-gsa yes, I think the smaller R is preferred. Thank you!

**Comment by weiwang-gsa** [comment]
@klohman this is ready for designer review: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/

**Comment by JessicaMarine1** [comment]
@weiwang-gsa I don't think so. If @rebekahperillo wants to add them on the individual questions, she can do that once we show her how to modify quiz content.

**Comment by klohman** [comment]
@weiwang-gsa I found a few places that still need the "GSA" or (R). 


1. On homepage in banner, the "GSA" is missing before "We offer SmartPay training" and there is no (R) mark on the first instance. 

![Screenshot 2023-09-11 at 12 29 24 PM](https://github.com/GSA/smartpay-training/assets/18366192/e905ecbc-08e1-4ea5-bcdf-ce2e22726c5d)

2. On Cardholder Travel Training Quiz page landing page, there is no (R) mark for first reference.
![Screenshot 2023-09-11 at 12 59 21 PM](https://github.com/GSA/smartpay-training/assets/18366192/2d9c068e-3fd2-4c6e-93ef-56356c057d5c)

3. In AOPC Travel Training Lesson 3, there is no (R) mark for first reference 
![Screenshot 2023-09-11 at 1 55 56 PM](https://github.com/GSA/smartpay-training/assets/18366192/92928272-7326-42e8-8889-859e576598da)

**Comment by weiwang-gsa** [comment]
@klohman great catch! I will update the code accordingly. For issue #2, I am wondering if we added R to quiz( the one with email input), should I remove R for the one (click email link with token), URL is actually the same, should we keep both, or treat them as same page only leave the first one?
<img width="1079" alt="image" src="https://github.com/GSA/smartpay-training/assets/119954777/de6d1325-878e-41ec-855a-b3fa8ad454f2">
<img width="1165" alt="image" src="https://github.com/GSA/smartpay-training/assets/119954777/023c1f8e-22d9-4946-896b-5e1ba6f4fa9e">

**Comment by klohman** [comment]
@weiwang-gsa I would add to the email entry page and still leave the other one. The URL is the same but displayed information is different enough to warrant this.

**Comment by weiwang-gsa** [comment]
@klohman issue addressed, ready for review: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/staging/

**Comment by klohman** [comment]
@A-L33 @rebekahperillo Ready for QA review.

**Comment by A-L33** [comment]
Done!
