### ISSUE TITLE
Launch Checklist | Training Site

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-training#297]
When it is time to launch the new training site, we'll need to:

- [x] Ensure production environment on cloud.gov is running and environment is properly set up (email links go to proper front end, frontend uses prod api)
- [x] Verify production database in clean state with latest quizzes, agencies, admins, etc
- [x] Ask cloud.gov pages how much time they need for the site launch governance process
- [x] Fill out Pages's [new site launch form](https://docs.google.com/forms/d/1ujDu9mUNmHuCG2Mx5JYFUaXthYrf304yMpBrGOEudMA/edit) with enough time for them to go through there governance process.
- [x] Create a ticket with GSA IT to move the domain record for training.smartpay.gov to point to cloud.gov pages
- [x] DNS changes

**Comment by JessicaMarine1** [comment]
Training site launched 10.5.2023 🚀🚀
